
POST localhost:38001/message/
Content-Type: application/json

{
  "fromUserId" : "100",
  "fromUsername" : "天涯兰",
  "toUserId" : "101",
  "toUsername" : "郑天民",
  "businessTypeCode" : "ORDER",
  "message" : "这是一条测试消息"
}

#####

GET localhost:38001/message
Content-Type: application/json

###

GET localhost:38001/message/99
Content-Type: application/json

###
