server:
  port: 18079
spring:
  application:
    name: business-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
      config:
        server-addr: 127.0.0.1:8848

seata:
  enable-auto-data-source-proxy: true
  application-id: ${spring.application.name}
  tx-service-group: business_service_group
  service:
    vgroupMapping:
      business_service_group: default
    grouplist:
      default: 127.0.0.1:8091
  registry:
    type: nacos
    nacos.:
      server-addr: localhost:8848
      application: seata-server
      group: SEATA_GROUP
  config:
    type: nacos
    nacos.:
      server-addr: localhost:8848
      group: SEATA_GROUP
