server:
  port: 18079
spring:
  application:
    name: business-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
      config:
        server-addr: 127.0.0.1:8848
