server:
  port: 38002
spring:
  application:
    name: message-service-sharding
  profiles:
    active: sharding-tables
mybatis:
  type-aliases-package: com.mf.message.service.entity
  mapper-locations: classpath:mapping/*Mapper.xml
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
    file: C:/dubbo/message-service/cache
  scan:
    base-packages: com.mf.message.service
message:
  service:
    version: 1.0.0
