spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.30.60.1:3306/customer_system?useInformationSchema=false&charset=utf8mb4&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  cloud:
    nacos:
      discovery:
        server-addr: 172.30.60.1:8848
      username: nacos
      password: nacos
    rabbitmq:
      host: 172.30.60.1
      port: 5672
      virtual-host: /hero_vh
      username: hero
      password: hero

mybatis:
  type-aliases-package: com.mf.projects.customer.system.entity
  mapper-locations: classpath:mapping/*Mapper.xml

xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://172.30.60.1:8080/xxl-job-admin
    executor:
      appname: customer-system
      logpath: /opt/xxl-job-executor/logs
      logretentiondays: 30



