server:
  port: ${port:8082}
spring:
  application:
    name: customer-service
  profiles:
    active: dev
mybatis:
  type-aliases-package: com.mf.projects.customer.system.entity
  mapper-locations: classpath:mapping/*Mapper.xml



