server:
  port: 8081
spring:
  application:
    name: customer-system
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
    file: C:/dubbo/customer-system/cache
  scan:
    base-packages: com.mf.projects.customer.system
customer:
  service:
    version: 1.0.0

xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: customer-system
      logpath: C:/xxl-job-executor/logs
      logretentiondays: 30
