
####
POST localhost:18003/auth/login
content-type: application/json

{
  "userId": "100",
  "userName": "ZP",
  "password": "1234"
}


####
DELETE localhost:18003/auth/logout/101
content-type: application/json
