server:
  port: 18002
spring:
  application:
    name: im-router
  redis:
    port: 6379
    host: localhost
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
    database: 0

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
    file: C:/dubbo/im-router/cache
  scan:
    base-packages: com.mf.im.router
im-router:
  service:
    version: 1.0.0
message:
  service:
    version: 1.0.0

