server:
  port: 18002
spring:
  application:
    name: im-router

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
    file: C:/dubbo/im-router/cache
  scan:
    base-packages: com.mf.im.router
im-router:
  service:
    version: 1.0.0
message:
  service:
    version: 1.0.0

