spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.30.60.1:3306/customer_hangzhou?characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  cloud:
    nacos:
      discovery:
        server-addr: 172.30.60.1:8848
      username: nacos
      password: nacos
  rabbitmq:
    host: 172.30.60.1
    port: 5672
    virtual-host: /hero_vh
    username: hero
    password: hero

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  metrics:
    export:
      prometheus:
        enabled: true
