server:
  port: 10011
spring:
  application:
    name: hangzhou-system
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  profiles:
    active: dev
