spring:
  application:
    name: auth-server
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: create

  profiles:
    active: dev
server:
  port: 18001
#logging:
#  level:
