server:
  port: 18076
spring:
  application:
    name: chat-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
      config:
        server-addr: 127.0.0.1:8848
  datasource:
    dynamic:
      primary: master
      druid:
        initial-size: 3
        min-idle: 3
        max-active: 40
        max-wait: 60000
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/chat_at?characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 1234
mybatis-plus:
  mapper-locations: classpath:mapperXml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

seata:
  enable-auto-data-source-proxy: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  service:
    vgroupMapping:
      ticket_service_group: default
    grouplist:
      default: 127.0.0.1:8091
  registry:
    type: nacos
    nacos.:
      server-addr: localhost:8848
      application: seata-server
      group: SEATA_GROUP
  config:
    type: nacos
    nacos.:
      server-addr: localhost:8848
      group: SEATA_GROUP
