spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /hero_vh
    username: hero
    password: hero

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
    file: C:/dubbo/integration-service/cache
  scan:
    base-packages: com.mf.integration.service.provider

