server:
  port:  ${port:8083}
spring:
  application:
    name: integration-service
  profiles:
    active: dev
integration:
  service:
    version: 1.0.0
customer:
  service:
    update:
      version: 1.0.0
