server:
  port: 38001
spring:
  application:
    name: message-service-traditional
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/message_service?useInformationSchema=false&charset=utf8mb4&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849
mybatis:
  type-aliases-package: com.mf.message.service.entity
  mapper-locations: classpath:mapping/*Mapper.xml
