server:
  port: 18004
spring:
  application:
    name: im-event
  profiles:
    active: sharding-tables

mybatis:
  type-aliases-package: com.mf.im.event.entity
  mapper-locations: classpath:mapping/*Mapper.xml
