spring:
  application:
    name: customer-system
  cloud:
    nacos:
      discovery:
        server-addr: 172.30.60.1:8848
      username: nacos
      password: nacos

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://172.30.60.1:2181
    file: /opt/customer-system/cache
  scan:
    base-packages: com.mf.projects.customer.system
customer:
  service:
    sync:
      version: 1.0.0

xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://172.30.60.1:8080/xxl-job-admin
    executor:
      appname: customer-system
      logpath: /opt/xxl-job-executor/logs
      logretentiondays: 30
