###
POST localhost:8082/oursouringsystem
Content-Type: application/json

{
  "systemName" : "杭州客服中心",
  "description" : "这是位于杭州的客服中心",
  "systemUrl" : "http://localhost:10011/customerstatffs/hangzhou/",
  "appId" : 3,
  "appKey" : "appKey_hangzhou",
  "appSecret" : "appSecret_hangzhou",
  "isDeleted": false
}


####
GET localhost:8082/oursouringsystem/3
Content-Type: application/json


####
DELETE localhost:8082/oursouringsystem/3
Content-Type: application/json
