spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    port: 6379
    host: localhost
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
    database: 0
  rabbitmq:
    publisher-confirms: true # 开启生产者确认模式：(confirm),投递到交换机，不论失败或者成功都回调
    publisher-returns: true
    host: localhost
    port: 5672
    virtual-host: /hero_vh
    username: hero
    password: hero

