server:
  port: 18080
spring:
  application:
    name: gateway-server
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      enabled: true
      discovery:
        locator:
          # ???????????????????????????
          enabled: true
          # ?????????????????????? false???? ??????????????
          lower-case-service-id: true
      routes:
        - id: baiduroute
          uri: https://www.baidu.com
          predicates:
            - Path=/baidu/**
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix=1 #????URL????????
            - PrefixPath=/chats #???????
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chats/**
          filters:
            - StripPrefix=1 #????URL????????
            - PrefixPath=/chats #???????
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.gateway: debug

