server:
  port: 18080
spring:
  application:
    name: gateway-server
  main:
    web-application-type: reactive
  datasource:
    dynamic:
      primary: master
      druid:
        initial-size: 3
        min-idle: 3
        max-active: 40
        max-wait: 60000
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/gateway_server?useInformationSchema=false&charset=utf8mb4&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
          username: root
          password: 1234
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8888
        port: 8719
    gateway:
      enabled: true
      discovery:
        locator:
          # 配置开启与DiscoveryClient整合
          enabled: true
          lower-case-service-id: true
#      default-filters:
#        - name: CircuitBreaker
#          args:
#            name: myCircuitBreaker
#            fallbackUri: forward:/fallback
      routes:
#        - id: circuitBreaker_filter
#          uri: http://localhost:8888
#          predicates:
#            - Path=/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: myCircuitBreaker
#                fallbackUri: forward:/fallback
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix=1
            - PrefixPath=/chats
#        - id: chat-service
#          uri: lb://chat-service
#          predicates:
#            - Path=/chats/**
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/chats
management:
  endpoints:
    web:
      exposure:
        include: "*"
mybatis-plus:
  mapper-locations: classpath:mapperXml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO


