server:
  port: 8082
spring:
  application:
    name: customer-service-provider
mybatis:
  type-aliases-package: com.mf.projects.customer.system.entity
  mapper-locations: classpath:mapping/*Mapper.xml




